Games-of-Switzerland/api.swissgamesgarden

composer.lock
```
Removing package drupal/core so that it can be re-installed and re-patched.
- Removing drupal/core (8.8.5)
Deleting web/core - deleted
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 3 updates, 0 removals
- Installing drupal/core (8.8.6): Loading from cache
- Applying patches for drupal/core
https://www.drupal.org/files/issues/2020-05-23/drupal-generalize-taxonomyindextid-filter-2429699-325.patch ([2429699] - Add Views EntityReference filter to be available for all entity reference fields)
https://www.drupal.org/files/issues/2018-07-05/2943172-kernel-test-base-3.patch …
```
=> update Drupal to 8.8.6

behat/Features/jsonapi/publisher.feature, behat/Features/jsonapi/publishers.feature, config/d8/sync/core.entity_form_display.node.game.default.yml, config/d8/sync/core.entity_form_display.taxonomy_term.publisher.default.yml, config/d8/sync/core.entity_view_display.node.game.default.yml, config/d8/sync/core.entity_view_display.node.game.teaser.yml, config/d8/sync/core.entity_view_display.taxonomy_term.publisher.default.yml, config/d8/sync/field.field.node.game.field_publishers.yml, config/d8/sync/field.field.taxonomy_term.publisher.field_path.yml, config/d8/sync/field.storage.node.field_publishers.yml, config/d8/sync/field.storage.taxonomy_term.field_path.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.taxonomy_term--publisher.yml, config/d8/sync/pathauto.pattern.publishers.yml, config/d8/sync/taxonomy.vocabulary.publisher.yml, web/modules/custom/gos_default_content/content/node/08952aa6-e079-496a-8efa-cbb8465d9315.json, web/modules/custom/gos_default_content/content/node/b7e315a4-65a1-4a34-b989-e2a5a96e1f22.json, web/modules/custom/gos_default_content/content/node/f13a9d5a-6bc0-437c-9d45-6b62d4b9f15b.json, web/modules/custom/gos_default_content/content/taxonomy_term/19b2fb28-468a-44ad-a03f-da4372e43539.json, web/modules/custom/gos_default_content/content/taxonomy_term/c16c1119-ae04-460c-9fed-e9e20d5785e7.json, web/modules/custom/gos_default_content/content/taxonomy_term/cff2f4a8-a1ac-40c0-b1c0-d5756b15c354.json, web/modules/custom/gos_migrate/migrations/migrate_plus.migration.gos_games.yml
Publisher are now an Entity that can be attached to Games.
- close #22 
- new Taxonomy Publisher
- Pathauto for Publisher
- Json:API exposition of Publisher
- 3 new default content for Publisher
- Publisher field in Games
- Farming Simulator default game attached to Publisher
- Behat coverage of entity
- Add migrations of publishers
1. `drush cim -y && drush cr`
2. Games should be able to have Publisher(s)
3. You should be able to create Publisher as Taxonomy
3. Publishers should be migrated on `drush mim gos_games`
=> Add Publishers to Games

behat/Features/jsonapi/sponsor.feature, behat/Features/jsonapi/sponsors.feature, config/d8/sync/core.entity_form_display.node.game.default.yml, config/d8/sync/core.entity_form_display.taxonomy_term.sponsor.default.yml, config/d8/sync/core.entity_view_display.node.game.default.yml, config/d8/sync/core.entity_view_display.node.game.teaser.yml, config/d8/sync/core.entity_view_display.taxonomy_term.sponsor.default.yml, config/d8/sync/field.field.node.game.field_sponsors.yml, config/d8/sync/field.field.taxonomy_term.sponsor.field_path.yml, config/d8/sync/field.storage.node.field_sponsors.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.taxonomy_term--sponsor.yml, config/d8/sync/pathauto.pattern.sponsors.yml, config/d8/sync/taxonomy.vocabulary.sponsor.yml, web/modules/custom/gos_default_content/content/node/f990d6af-d50d-4b35-a79a-72a1e12a7422.json, web/modules/custom/gos_default_content/content/taxonomy_term/08e81e70-8dba-4cc2-bc7d-b1ee13d7c9a5.json, web/modules/custom/gos_default_content/content/taxonomy_term/6bfe8b95-305d-4abb-924c-ec2ca6fc9895.json, web/modules/custom/gos_default_content/content/taxonomy_term/dc78845d-ba97-4fe3-889b-30680eedcd91.json, web/modules/custom/gos_migrate/migrations/migrate_plus.migration.gos_games.yml
Sponsor are now an Entity that can be attached to Games.
- close #23 
- new Taxonomy Sponsor
- Pathauto for Sponsor
- Json:API exposition of Sponsor
- 3 new default content for Sponsor
- Sponsor field in Games
- Persephone default game attached to a Sponsor
- Behat coverage of entity
- Add migrations of Sponsor
1. `drush cim -y && drush cr`
2. Games should be able to have Sponsor(s)
3. You should be able to create Sponsor as Taxonomy
3. Sponsors should be migrated on `drush mim gos_games`
=> Add Sponsors to Games

behat/Features/login/login.feature, docker-compose.yml
Mysql Docker base image has made a major breaking change wihtout really noticing people. They are now auto-escaping databasename containing `_`.
https://github.com/docker-library/mysql/pull/500#issuecomment-631141798
This leads our `MYSQL_DATABASE: drupal\_%` to generate bad `GRANT` by double escaping and break our builds.
To fix this, just remove our own escaping.
- close #45
=> Fix Travis MariaDB connection

behat/Features/elasticsearch/search.games.feature, behat/Features/elasticsearch/search.games.genres.facets.feature, behat/Features/elasticsearch/search.games.genres.feature, behat/Features/elasticsearch/search.games.platforms.facets.feature, behat/Features/elasticsearch/search.games.platforms.feature, web/modules/custom/gos_elasticsearch/src/Plugin/rest/ResourceValidator/ElasticGamesResourceValidator.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php, web/swagger/swagger.json
- close #7 
- init #4 
New `page` mandatory argument to `/search/games`.
This new argument must be an Integer zeroOrPositive.
Usage: `http://api.gos.test/search/games?page=0`
New `sort` capability that only suppoprt - for now - `_score`.
Usage: `http://api.gos.test/search/games?page=0&sort[desc]=_score`
Usage: `http://api.gos.test/search/games?page=0&sort[asc]=_score`
=> Add mandatory page to `/search/games` & init sort feature

behat/Features/elasticsearch/search.games.genres.facets.feature, behat/Features/elasticsearch/search.games.genres.feature, behat/Features/elasticsearch/search.games.platforms.facets.feature, behat/Features/elasticsearch/search.games.platforms.feature, behat/Features/elasticsearch/search.games.stores.facets.feature, config/d8/sync/core.entity_form_display.taxonomy_term.genre.default.yml, config/d8/sync/core.entity_form_display.taxonomy_term.platform.default.yml, config/d8/sync/core.entity_view_display.taxonomy_term.genre.default.yml, config/d8/sync/core.entity_view_display.taxonomy_term.platform.default.yml, config/d8/sync/field.field.taxonomy_term.genre.field_slug.yml, config/d8/sync/field.field.taxonomy_term.platform.field_slug.yml, config/d8/sync/field.storage.taxonomy_term.field_slug.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.taxonomy_term--genre.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.taxonomy_term--platform.yml, web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/GameNodeIndex.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/GameNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/ResourceValidator/ElasticGamesResourceValidator.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php, web/modules/custom/gos_migrate/gos_migrate.info.yml, web/modules/custom/gos_site/gos_site.module, web/swagger/swagger.json
- Remove usage of UUIDs for filtering `search/games` (genres & platforms) and use a slugified value instead.
- Automatically generate a slug for those entity on insert (if field empty)
- close #52
- close #53 
Now instead of using UUID for Genres & Platforms, you should use a slug.
Remove many uuid from ES as not needed anymore.
=> Slugify Genres & Platforms

config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--game.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--people.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--studio.yml
update json:api fields name by removing prefix `field_` excepted for `path` (as original `path` already exists and would collide)
=> update json:api fields name normalization

web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/NodeIndexBase.php
Will always use the proper configured index_prefix and not a wildcard #66
- close #66
=> ensure when generating pattern for Elasticsearch

behat/Features/elasticsearch/search.games.locations.facets.feature, web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/NodeIndexBase.php
We have to index "unpublished" node and filter them out from the REST bridge.
Indeed, if we don't index them, then the Elasticsearch Helper will not be able to "update" the node to "Publish" from Drupal. As the Helper only try an "update" call and not a "create or update" one. Therefore we should always index every node then filter them out if unpublished.
=> index unpublished item

behat/Features/elasticsearch/search.games.release_years.facets.feature, behat/Features/elasticsearch/search.games.release_years.feature, behat/Fixtures/elasticsearch/schemaref.search.games.release_years.facets.json, web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/GameNodeIndex.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/GameNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/ResourceValidator/ElasticGamesResourceValidator.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php, web/modules/custom/gos_rest/src/Plugin/rest/ResourceValidator/BaseValidator.php, web/swagger/swagger.json
- close #43 
1. Access the Game endpoint `/search/games?page=0`
You should now see a new bucket `aggregations.aggs_all.all_filtered_release_years_histogram`.
```json
"all_filtered_release_years_histogram": {
"doc_count": 4,
"all_nested_release_years": {
"doc_count": 3,
"releases_over_time": {
"buckets": [{
"key_as_string": "2017",
"key": 1483228800000,
"doc_count": 1
},
{
"key_as_string": "2018",
"key": 1514764800000,
"doc_count": 2
}
]
}
}
},
```
2. You should also be able to filter games by `release_year`
```
/search/games?page=0&release_year=2017
```
If applicable, add swagger API endpoints to help explain the usage.
=> Release years aggregations & filtering

behat/Features/elasticsearch/search.games.q.feature, web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/GameNodeIndex.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/ResourceValidator/ElasticGamesResourceValidator.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php, web/swagger/swagger.json
Allow fulltext games title search.
- close #5
1. Use the new `q` parameter on the `search/games` endpoint.
2. Go to `search/games?page=0&q=farming`
The results should be filtered by `farming` keyword.
- A new `string` property named `q` is available on `search/games`
=> fulltext search of games

README.md, behat/Features/redirects/game.feature, behat/Features/redirects/people.feature, behat/Features/redirects/studio.feature, web/modules/custom/gos_site/gos_site.services.yml, web/modules/custom/gos_site/src/EventSubscriber/BaseEntityReroute.php, web/modules/custom/gos_site/src/EventSubscriber/NodeEntityReroute.php, web/modules/custom/gos_site/src/UrlBuilderNextJs.php, web/sites/default/development.settings.php
Be sure Games, Studios & People link from Drupal will redirect to React/Next decoupled website.
- close #100 
1. Access to a game canonical `/node/x`
```
/**
* Base URL of the Next App.
*
* This value should not contain a leading slash (/).
*
* @var string
*/
$config['frontend']['base_url'] = 'https://gos.museebolo.ch';
```
=> ensure games, people & studio are redirected to React/Next app from Drupal 'Canonical access'

web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php
I need a page size to be set to an even number dividable by 3 and 4. That way I can set a grid of 1-2-3-4 columns.
- none
click on "Merge pull request"
If applicable, add screenshots to help explain the task.
If applicable, add swagger API endpoints to help explain the usage.
=> Set page size to 24 games instead of 25 in Elasticsearch

composer.json, composer.lock, config/d8/sync/core.extension.yml, config/d8/sync/file_mdm.file_metadata_plugin.getimagesize.yml, config/d8/sync/file_mdm.settings.yml, config/d8/sync/file_mdm_exif.file_metadata_plugin.exif.yml, config/d8/sync/file_mdm_font.file_metadata_plugin.font.yml, config/d8/sync/image.style.placeholder_30x30.yml, config/d8/sync/image_effects.settings.yml, config/d8/sync/webp.settings.yml
Webp image can be requested by using .webp as extension of existing IamgeStyles.
Example, `http://api.gos.test/sites/default/files/styles/downscale_675x500/public/games/2020-10/generateImage_eVPAAW.jpg?itok=27yEZ1cP` should be requested as `http://api.gos.test/sites/default/files/styles/downscale_675x500/public/games/2020-10/generateImage_eVPAAW.webp?itok=27yEZ1cP`
You can replace the `.jpg?` & `.webp?`.
=> Serve webp images

.github/workflows/styles.yml
Fix usage of Composer v2 which is not possible for now - because of Drupal Console requirements.
=> force usage of composer V1 on Github Actions

behat/Features/elasticsearch/search.games.release_year_range.feature, web/modules/custom/gos_elasticsearch/src/Plugin/rest/ResourceValidator/ElasticGamesResourceValidator.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php, web/swagger/swagger.json
Add a new filter to allow "between" filter via Release Widget
1. http://api.gos.test/search/games?page=0&release_year_range[start]=2001&release_year_range[end]=2018
New parameters `release_year_range[start]` & `release_year_range[end]`
=> Add a new filter `release_year_range` to `/search` endpoint

composer.json, composer.lock, config/d8/sync/admin_toolbar_tools.settings.yml
Update modules dependencies for Drupal 9
- update drupal/admin_toolbar (2.4.0 => 3.0.0)
- update drupal/bamboo_twig (4.1.0 => 5.0.0-alpha1)
- update drupal/new_relic_rpm (1.3.0 => 2.1.0)
- update drupal/consumer_image_styles (3.1.0 => 4.0.0)
=> Update modules for Drupal 9 readiness

CHANGELOG.md, web/modules/custom/gos_migrate/README.md, web/modules/custom/gos_migrate/migrations/gos_games.update.website.yml
Use the Website column to fill the Website field
- Games-of-Switzerland/gos-website#84
1. Run the new migration update on a databse with already migrated content
2. Website field will use the Website CSV column if not empty
=> add a migration update to fillup Website field on Games - Games-of-Switzerland/gos-website#84

CHANGELOG.md, web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/GameNodeIndex.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/GameNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php
add facets extra data for platform name, location name & genre name 
- close Games-of-Switzerland/swissgamesgarden#50
1. Fetch the search of games, the facets of platforms, genres & locations will not have extra data containing the name
```
http://localhost:8089/search/games?page=0
```
```
{
"key": "zurich",
"doc_count": 1,
"locations_facet_data": {
"hits": {
"total": 1,
"max_score": 1,
"hits": [
{
"_index": "development_gos_node_game_en",
"_type": "node",
"_id": "12",
"_nested": {
"field": "locations",
"offset": 0
},
"_score": 1,
"_source": {
"name": "Zürich"
}
}
]
}
}
}
```
```
{
"key": "ios",
"doc_count": 2,
"platforms_facet_data": {
"hits": {
"total": 2,
"max_score": 1,
"hits": [
{
"_index": "development_gos_node_game_en", …
```
=> add facets extra data for platform name, location name & genre name

CHANGELOG.md, composer.json, composer.lock
update Drupal 9.3.7 => 9.3.12 with all dependencies
```
Lock file operations: 0 installs, 30 updates, 0 removals
- Upgrading alexandresalome/mailcatcher (v1.3.2 => v1.4.0)
- Upgrading behat/mink (v1.9.0 => v1.10.0)
- Upgrading behat/mink-selenium2-driver (v1.5.0 => v1.6.0)
- Upgrading behat/transliterator (v1.3.0 => v1.5.0)
- Upgrading composer/composer (2.2.7 => 2.2.12)
- Upgrading consolidation/annotated-command (4.5.2 => 4.5.4)
- Upgrading drupal/consumer_image_styles (4.0.6 => 4.0.7)
- Upgrading drupal/core (9.3.7 => 9.3.12)
- Upgrading drupal/core-composer-scaffold (9.3.7 => 9.3.12)
- Upgrading drupal/core-dev (9.3.7 => 9.3.12)
- Upgrading drupal/core-project-message (9.3.7 => 9.3.12)
- Upgrading drupal/core-recommended (9.3.7 => 9.3.12)
- Upgrading drupal/gin (3.0.0-beta1 => …
```
=> update Drupal 9.3.7 => 9.3.12 with all dependencies

CHANGELOG.md, composer.lock, config/d8/sync/pathauto.pattern.games.yml, config/d8/sync/pathauto.pattern.pages.yml, config/d8/sync/pathauto.pattern.people.yml, config/d8/sync/pathauto.pattern.studio.yml
update PHP dependencies 05.05.2022
```
Lock file operations: 0 installs, 12 updates, 0 removals
- Upgrading consolidation/annotated-command (4.5.4 => 4.5.5)
- Upgrading drupal/drupal-driver (v2.1.1 => v2.1.2)
- Upgrading drupal/drupal-extension (v4.1.0 => v4.2.1)
- Upgrading drupal/jsonapi_hypermedia (1.6.0 => 1.7.0)
- Upgrading drupal/migrate_plus (5.2.0 => 5.3.0)
- Upgrading drupal/pathauto (1.9.0 => 1.10.0)
- Upgrading phpstan/phpdoc-parser (1.4.4 => 1.5.1)
- Upgrading symfony/config (v4.4.37 => v4.4.41)
- Upgrading symfony/finder (v4.4.37 => v4.4.41)
- Upgrading symfony/phpunit-bridge (v5.4.7 => v5.4.8)
- Upgrading symfony/property-access (v5.4.7 => v5.4.8)
- Upgrading symfony/string (v6.0.3 => v6.0.8)
```
```
---------- ----------- --------------- ------------------------------------ …
```
=> update PHP dependencies 05.05.2022

CHANGELOG.md, README.md, behat/Features/redirects/game.feature, behat/Features/redirects/people.feature, behat/Features/redirects/studio.feature, behat/Features/sitemap.feature, composer.json, composer.lock, config/d8/sync/simple_sitemap.bundle_settings.default.node.game.yml, config/d8/sync/simple_sitemap.bundle_settings.default.node.page.yml, config/d8/sync/simple_sitemap.bundle_settings.default.node.people.yml, config/d8/sync/simple_sitemap.bundle_settings.default.node.studio.yml, config/d8/sync/simple_sitemap.custom_links.default.yml, config/d8/sync/simple_sitemap.settings.yml, config/d8/sync/simple_sitemap.sitemap.default.yml, config/d8/sync/simple_sitemap.sitemap.index.yml, config/d8/sync/simple_sitemap.type.default_hreflang.yml, config/d8/sync/simple_sitemap.type.index.yml, config/d8/sync/simple_sitemap.variants.default_hreflang.yml, web/modules/custom/gos_site/src/Plugin/simple_sitemap/UrlGenerator/NextJsUrlGenerator.php, web/modules/custom/gos_site/src/UrlBuilderNextJs.php, web/sites/default/settings.development.php, web/sites/default/settings.test.php
```bash
composer require drupal/simple_sitemap:^4.1
```
```bash
Lock file operations: 0 installs, 1 update, 0 removals
- Upgrading drupal/simple_sitemap (3.11.0 => 4.1.2)
```
```bash
---------------- ----------- --------------- ---------------------------------
Module           Update ID   Type            Description
---------------- ----------- --------------- ---------------------------------
simple_sitemap   8401        hook_update_n   8401 - Change the
simple_sitemap ID column to
serial.
simple_sitemap   8402        hook_update_n   8402 - Install new
simple_sitemap_type and
simple_sitemap configuration
entities.
simple_sitemap   8403        hook_update_n   8403 - Migrate the
default_hreflang sitemap type
and its …
```
=> update module drupal/simple_sitemap (3.11.0 => 4.1.2)

CHANGELOG.md, composer.lock, config/d8/sync/editor.editor.basic_html.yml, config/d8/sync/editor.editor.full_html.yml, config/d8/sync/filter.format.basic_html.yml, config/d8/sync/filter.format.full_html.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--game.yml
```bash
composer update drupal/file_mdm drupal/simple_sitemap drupal/metatag drupal/image_effects drupal/field_group drupal/crop drupal/consumers drupal/bamboo_twig
```
```bash
Package operations: 0 installs, 8 updates, 0 removals
- Downloading drupal/bamboo_twig (5.1.0)
- Downloading drupal/consumers (1.14.0)
- Downloading drupal/field_group (3.4.0)
- Downloading drupal/crop (2.3.0)
- Downloading drupal/file_mdm (2.5.0)
- Downloading drupal/image_effects (3.4.0)
- Downloading drupal/metatag (1.22.0)
- Downloading drupal/simple_sitemap (4.1.3)
```
```bash
----------- ----------- --------------- ----------------------------------
Module      Update ID   Type            Description
----------- ----------- --------------- …
```
=> update 8 Drupal modules minors/patches

CHANGELOG.md, config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--game.yml
fix field_cantons json:api public name to be 'cantons'
=> fix field_cantons json:api public name to be 'cantons'

CHANGELOG.md, behat/Context/Drupal/XmlContext.php, composer.lock, config/d8/sync/views.view.content.yml, web/.htaccess, web/sites/default/default.settings.php
update drupal/core (9.5.3 => 9.5.11)
```
composer update "drupal/core-*" --with-all-dependencies
```
```
Lock file operations: 1 install, 45 updates, 1 removal
- Removing laminas/laminas-diactoros (2.14.0)
- Upgrading behat/mink (v1.10.0 => v1.11.0)
- Upgrading behat/mink-selenium2-driver (v1.6.0 => v1.7.0)
- Upgrading composer/ca-bundle (1.3.5 => 1.4.0)
- Upgrading composer/composer (2.2.19 => 2.2.23)
- Upgrading composer/spdx-licenses (1.5.7 => 1.5.8)
- Upgrading composer/xdebug-handler (2.0.5 => 3.0.3)
- Upgrading dealerdirect/phpcodesniffer-composer-installer (v0.7.2 => v1.0.0)
- Upgrading doctrine/reflection (1.2.3 => 1.2.4)
- Upgrading drupal/coder (8.3.16 => 8.3.22)
- Upgrading drupal/core (9.5.3 => 9.5.11)
- Upgrading drupal/core-composer-scaffold (9.5.3 => 9.5.11)
- Upgrading …
```
=> update drupal/core (9.5.3 => 9.5.11)

CHANGELOG.md, composer.json, composer.lock, config/d8/sync/core.extension.yml, config/d8/sync/save_edit.settings.yml
add & setup module Save & Edit
1. Newer button on node creation/edition that allows to stay on Drupal upon saving
=> add & setup module Save & Edit
