web/modules/custom/gos_site/gos_site.module
=> redirect user to /admin/content on login

composer.json, composer.lock, config/d8/sync/views.view.content.yml, web/modules/custom/gos_migrate/gos_migrate.info.yml, web/modules/custom/gos_migrate/migrations/migrate_plus.migration.gos_games.yml
Migrate images by downloading the Screenshot link form CSV.
- close #39
- Download the screenshot link and create an image when URL give an image
- Add the first Image of the collection in the Views of Games
Many games from the CSV does not provide a working image link
=> Migrate images

behat/Features/elasticsearch/search.games.sort.feature, web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/GameNodeIndex.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/GameNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/ResourceValidator/ElasticGamesResourceValidator.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php, web/swagger/swagger.json
Add release date, changed & title sort capabilities
- close #4 
If applicable, add screenshots to help explain the task.
Usage: 
- `http://api.gos.test/search/games?page=0&sort[desc]=releases.date`
- `http://api.gos.test/search/games?page=0&sort[asc]=title.keyword`
- `http://api.gos.test/search/games?page=0&sort[asc]=changed`
=> Finalise sort capabilities

web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php
Add platforms & genres UUIDs to aggregations for easier filtering usage by frontenders.
- close #50
=> add UUDIs to aggregations Platforms & Genres

composer.lock
=> update all dependencies

config/d8/sync/core.entity_form_display.node.game.default.yml, config/d8/sync/core.entity_view_display.node.game.default.yml, config/d8/sync/core.entity_view_display.node.game.teaser.yml, config/d8/sync/core.extension.yml, config/d8/sync/field.field.node.game.field_completeness.yml, config/d8/sync/field.storage.node.field_completeness.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--game.yml, config/d8/sync/views.view.content.yml, psalm.xml, web/autoload-psalm.php, web/modules/custom/gos_game/gos_game.info.yml, web/modules/custom/gos_game/gos_game.module, web/modules/custom/gos_game/gos_game.services.yml, web/modules/custom/gos_game/src/CompletenessCalculator.php, web/modules/custom/gos_game/src/Plugin/Field/FieldType/CompletenessItem.php, web/modules/custom/gos_game/src/Plugin/Field/FieldWidget/CompletenessWidget.php, web/modules/custom/gos_game/tests/src/Unit/CompletenessCalculatorTest.php, web/phpunit.xml, web/themes/gos_admin/css/gos-admin.css
automatic completness calculation.
- close #41 
1. On save/update/create a Game, a completness score should be calculated
2. The views listing Games should allow filtering by completness score
`completeness` is a public available property
=> Completness field

config/d8/sync/core.entity_form_display.node.game.default.yml, config/d8/sync/core.entity_view_display.node.game.default.yml, config/d8/sync/core.entity_view_display.node.game.teaser.yml, config/d8/sync/field.field.node.game.field_social_networks.yml, config/d8/sync/field.storage.node.field_social_networks.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--game.yml, web/modules/custom/gos_default_content/content/node/12b7a617-4c66-4fb1-adf0-0ad70b775b9c.json, web/modules/custom/gos_game/src/CompletenessCalculator.php, web/modules/custom/gos_game/tests/src/Unit/CompletenessCalculatorTest.php, web/modules/custom/gos_migrate/migrations/migrate_plus.migration.gos_games.yml, web/modules/custom/gos_migrate/src/Plugin/migrate/process/TwitterHandle.php, web/modules/custom/gos_site/src/Plugin/Field/FieldFormatter/SocialFieldFormatter.php, web/modules/custom/gos_site/src/Plugin/Field/FieldType/SocialItem.php, web/modules/custom/gos_site/src/Plugin/Field/FieldWidget/SocialDefaultWidget.php
=> Add social fields to games

behat/Fixtures/elasticsearch/schemaref.search.games.platforms.facets.json, web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/PeopleNodeIndex.php, web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/StudioNodeIndex.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/GameNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/PeopleNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/StudioNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticAutocompleteResource.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php
add the is_published properties to all indices and use it as must-fil…ter condition on all rest ressource
- close #67
=> add the is_published properties to all indices and use it as filter

composer.json, composer.lock, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php
- Update all dependencies allongside with drupal/core to 8.9.4
```
Package operations: 0 installs, 60 updates, 1 removal
- Removing behat/mink-extension (2.3.1)
- Updating composer/package-versions-deprecated (1.5.1 => 1.11.99): Downloading (100%)
- Updating symfony/finder (v3.4.42 => v3.4.44): Loading from cache
- Updating drupal/console-extend-plugin (0.9.3 => 0.9.4): Loading from cache
- Updating symfony/polyfill-php80 (v1.17.0 => v1.18.1): Loading from cache
- Updating symfony/deprecation-contracts (v2.1.2 => v2.1.3): Loading from cache
- Updating symfony/polyfill-intl-normalizer (v1.17.0 => v1.18.1): Loading from cache
- Updating symfony/polyfill-intl-grapheme (v1.17.0 => v1.18.1): …
```
=> update drupal/core (8.9.1 => 8.9.4) with all dependencies (60 updates)

composer.lock
=> update drupal/core-recommended 8.9.4 -> 8.9.5 with dependencies

behat/Features/elasticsearch/search.autocomplete.q.feature, web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/GameNodeIndex.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/GameNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticAutocompleteResource.php
Improve the search with related games by people
- close #77
1. call `http://api.gos.test/autocomplete?q=wuthrer`
2. Should give you Wuthrer as People but also related games of Wuthrer
=> Allow autocomplete cross search games by people studios

config/d8/sync/core.entity_form_display.node.game.default.yml, config/d8/sync/core.entity_view_display.node.game.default.yml, config/d8/sync/core.entity_view_display.node.game.teaser.yml, config/d8/sync/field.field.node.game.field_contextual_links.yml, config/d8/sync/field.storage.node.field_contextual_links.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--game.yml, web/modules/custom/gos_default_content/content/node/12b7a617-4c66-4fb1-adf0-0ad70b775b9c.json, web/modules/custom/gos_default_content/content/node/f990d6af-d50d-4b35-a79a-72a1e12a7422.json, web/modules/custom/gos_game/src/CompletenessCalculator.php, web/modules/custom/gos_migrate/migrations/migrate_plus.migration.gos_games.yml, web/modules/custom/gos_migrate/src/Plugin/migrate/process/ContextualLinksMapper.php, web/modules/custom/gos_site/src/Plugin/Field/FieldFormatter/ContextualLinkFieldFormatter.php, web/modules/custom/gos_site/src/Plugin/Field/FieldType/ContextualLinkItem.php, web/modules/custom/gos_site/src/Plugin/Field/FieldWidget/ContextualLinkDefaultWidget.php
Add Contextual links on games.
- close #60 
1. the new `field_contextual_links` exists and allow :
> - presskit
> - devlog
> - online_play
> - download_page
> - direct_download
> - box_art
2. in JSON:API, this same field is named `contextual_links`
```
drush mim gos_people && drush mim gos_studios && drush mim gos_platforms && drush mim gos_genres && drush mim gos_locations && drush mim gos_languages && drush mim gos_publishers && drush mim gos_sponsors && drush mim gos_trailers && drush mim gos_games
```
=> Contextual links

config/d8/sync/core.entity_form_display.node.game.default.yml, config/d8/sync/core.entity_view_display.node.game.default.yml, config/d8/sync/core.entity_view_display.node.game.teaser.yml, config/d8/sync/field.field.node.game.field_credits.yml, config/d8/sync/field.storage.node.field_credits.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--game.yml, web/modules/custom/gos_default_content/content/node/f990d6af-d50d-4b35-a79a-72a1e12a7422.json, web/modules/custom/gos_game/src/CompletenessCalculator.php, web/modules/custom/gos_migrate/migrations/migrate_plus.migration.gos_games.yml
Add Credits on games.
- close #63
1. the new `field_credits` exists formatted content
2. in JSON:API, this same field is named `credits`
```
drush mim gos_people && drush mim gos_studios && drush mim gos_platforms && drush mim gos_genres && drush mim gos_locations && drush mim gos_languages && drush mim gos_publishers && drush mim gos_sponsors && drush mim gos_trailers && drush mim gos_games
```
=> Credits field

composer.json, web/modules/custom/gos_migrate/migrations/migrate_plus.migration.gos_games.yml, web/modules/custom/gos_migrate/src/Plugin/migrate/process/SkipOnFileNotExists.php, web/modules/custom/gos_migrate/src/Plugin/migrate/process/SkipOnFileNotImage.php
Ensure Screenshots/Covers downloaded by migrations works and prevent crash of rows when images/files is not available (or worst ... is not an image because of redirections to html page).
1. Run the migration process, you should not have any Ignored games
=> Games cover screenshots migration fixed ignored

behat/Features/jsonapi/studio.feature, behat/Fixtures/elasticsearch/schemaref.autocomplete.wide.json, config/d8/sync/pathauto.pattern.studio.yml
update Studios pathauto from /studio/xxx to /studios/xxx
- close #88
=> pluralise Studios pathauto

Dockerfile, behat/Context/Drupal/DatabaseContext.php, behat/Context/Drupal/DebugContext.php, behat/Context/Drupal/MailContext.php, behat/Context/Drupal/WatchdogContext.php, composer.json, composer.lock, phpmd.xml, web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/NodeIndexBase.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/GameNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/PeopleNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/StudioNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticAutocompleteResource.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticResourceBase.php, web/modules/custom/gos_game/src/ReleasesCompiler.php, web/modules/custom/gos_migrate/src/Plugin/migrate/process/SkipOnFileNotExists.php, web/modules/custom/gos_migrate/src/Plugin/migrate/process/SkipOnFileNotImage.php, web/modules/custom/gos_rest/src/Plugin/rest/ResourceValidator/BaseValidator.php, web/modules/custom/gos_test/src/Traits/NodeTestTrait.php
Update to 8.9.7 with all dependencies
```
Package operations: 1 install, 31 updates, 0 removals
- Updating cweagans/composer-patches (1.6.7 => 1.7.0): Downloading (100%)
- Updating zaporylie/composer-drupal-optimizations (1.1.1 => 1.1.2): Downloading (100%)
- Updating symfony/string (v5.1.5 => v5.1.7): Downloading (100%)
- Updating symfony/deprecation-contracts (v2.1.3 => v2.2.0): Downloading (100%)
- Updating symfony/inflector (v5.1.5 => v5.1.7): Loading from cache
- Updating phpdocumentor/type-resolver (1.3.0 => 1.4.0): Downloading (100%)
- Updating phpdocumentor/reflection-docblock (5.2.1 => 5.2.2): Downloading (100%)
- Updating symfony/var-dumper (v4.4.13 => v4.4.15): Downloading (100%)
- …
```
=> Feature/core update 8.9.7

Dockerfile, README.md, composer.json, composer.lock, config/d8/sync/core.extension.yml, config/d8/sync/new_relic_rpm.settings.yml, config/deploy.rb, docker-compose.override-example.yml, docker-compose.yml, docker/newrelic.sh
Add New Relic per-environment using the php-agent & container-daemon
- close #94 
1. Deploy the branch
1. Access to New Relic and metrics should be fetched
=> Docker New Relic Integration per-env

behat.yml, behat/Context/Drupal/RedirectContext.php, behat/Features/redirects/genre.feature, behat/Features/redirects/language.feature, behat/Features/redirects/location.feature, behat/Features/redirects/platform.feature, behat/Features/redirects/publisher.feature, behat/Features/redirects/sponsor.feature, web/modules/custom/gos_site/gos_site.services.yml, web/modules/custom/gos_site/src/EventSubscriber/BaseEntityReroute.php, web/modules/custom/gos_site/src/EventSubscriber/TaxonomyEntityReroute.php
Shutdown access to canonical content that we don't want to expose.
- close #98
=> Disable Canonical Access to Genre, Platform. Language, Location, Publisher & Sponsor Taxonomies

behat/Features/elasticsearch/search.games.feature, behat/Features/jsonapi/game.feature, config/d8/sync/image.style.3x2_330x220.yml, config/d8/sync/image.style.3x2_660x440.yml, config/d8/sync/image.style.downscale_1350x1000.yml, config/d8/sync/image.style.downscale_2560x1600.yml, config/d8/sync/image.style.downscale_330x660.yml, config/d8/sync/image.style.downscale_675x500.yml, config/d8/sync/image.style.placeholder_30x30.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--game.yml, web/modules/custom/gos_default_content/src/EventSubscriber/ConsumersSubscriber.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/GameNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/Traits/NormalizerImagesDerivativesTrait.php, web/modules/custom/gos_site/gos_site.install
Add Images Styles as requested by @tonifisler 
- close #89 
1. Images styles are in `medias` into ES endpoints
1. Images styles are in `images` when included on JSON:api
=> Image styles

behat/Features/elasticsearch/search.games.feature, behat/Features/jsonapi/game.feature, composer.json, composer.lock, config/d8/sync/core.extension.yml, config/d8/sync/file_mdm.file_metadata_plugin.getimagesize.yml, config/d8/sync/file_mdm.settings.yml, config/d8/sync/file_mdm_exif.file_metadata_plugin.exif.yml, config/d8/sync/file_mdm_font.file_metadata_plugin.font.yml, config/d8/sync/image.style.3x2_330x220.yml, config/d8/sync/image.style.3x2_660x440.yml, config/d8/sync/image.style.downscale_1350x1000.yml, config/d8/sync/image.style.downscale_2560x1600.yml, config/d8/sync/image.style.downscale_330x660.yml, config/d8/sync/image.style.downscale_675x500.yml, config/d8/sync/image.style.placeholder_30x30.yml, config/d8/sync/image_effects.settings.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--game.yml, web/modules/custom/gos_default_content/src/EventSubscriber/ConsumersSubscriber.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/GameNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/Traits/NormalizerImagesDerivativesTrait.php, web/modules/custom/gos_site/gos_site.install
Merge after #107 
Add a Gaussian Blur effect to the Placeholder image Style.
=> Add gaussian blur placeholder style

composer.lock
=> update drupal/core-recommended (8.9.7 => 8.9.8)

composer.lock
Update all dependencies. 
`composer update`
```
Package operations: 0 installs, 42 updates, 0 removals
- Updating zaporylie/composer-drupal-optimizations (1.1.2 => 1.2.0): Loading from cache
- Updating composer/package-versions-deprecated (1.11.99 => 1.11.99.1): Loading from cache
- Updating symfony/polyfill-php80 (v1.18.1 => v1.20.0): Loading from cache
- Updating symfony/polyfill-intl-normalizer (v1.18.1 => v1.20.0): Loading from cache
- Updating symfony/polyfill-intl-grapheme (v1.18.1 => v1.20.0): Loading from cache
- Updating symfony/string (v5.1.7 => v5.1.8): Loading from cache
- Updating symfony/inflector (v5.1.7 => v5.1.8): Loading from cache
- Updating symfony/var-dumper (v4.4.15 => …
```
=> update all dependencies (42 packages updated)

behat/Features/elasticsearch/search.games.feature, config/d8/sync/core.entity_form_display.node.game.default.yml, config/d8/sync/core.entity_view_display.node.game.default.yml, config/d8/sync/core.entity_view_display.node.game.teaser.yml, config/d8/sync/field.field.node.game.field_player.yml, config/d8/sync/field.storage.node.field_player.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--game.yml, web/modules/custom/gos_default_content/content/node/12b7a617-4c66-4fb1-adf0-0ad70b775b9c.json, web/modules/custom/gos_default_content/content/node/9bb9538f-5b75-4dc0-99b1-ff11d4e2abdd.json, web/modules/custom/gos_default_content/content/node/f990d6af-d50d-4b35-a79a-72a1e12a7422.json, web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/GameNodeIndex.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/GameNormalizer.php, web/modules/custom/gos_site/src/Plugin/Field/FieldFormatter/PlayerFieldFormatter.php, web/modules/custom/gos_site/src/Plugin/Field/FieldType/PlayerItem.php, web/modules/custom/gos_site/src/Plugin/Field/FieldWidget/PlayerDefaultWidget.php
- Add a field player as requested by @CamilleLetang 
- close #115 
1. Access to a game via JsonAPI
2. This game should have the Player(s) min/max data
new `player` property on games
=> Filed players on games

.github/workflows/styles.yml, Dockerfile, composer.json, docker-compose.yml, patches/doctrine-annotations--fix-lookahead-php74.patch
update to php 7.4 & mariadb 10.4
=> update to php 7.4 & mariadb 10.4

composer.lock
```
Package operations: 1 install, 44 updates, 0 removals
- Updating symfony/finder (v3.4.46 => v3.4.47): Downloading (100%)
- Updating drupal/console-extend-plugin (0.9.4 => 0.9.5): Downloading (100%)
- Updating symfony/string (v5.1.8 => v5.2.0): Downloading (100%)
- Updating symfony/inflector (v5.1.8 => v5.2.0): Loading from cache
- Updating symfony/dom-crawler (v3.4.46 => v3.4.47): Loading from cache
- Updating symfony/css-selector (v3.4.46 => v3.4.47): Loading from cache
- Updating symfony/var-dumper (v4.4.16 => v4.4.17): Downloading (100%)
- Installing symfony/polyfill-php73 (v1.20.0): Loading from cache
- Updating nikic/php-parser (v4.10.2 => v4.10.3): Loading from cache
- Updating …
```
=> update to Drupal 8.9.11 with all dependencies

.github/workflows/styles.yml, composer.json, composer.lock
Update all dependencies
```
Package operations: 1 install, 15 updates, 0 removals
- Installing zaporylie/composer-drupal-optimizations (1.2.0): Loading from cache
- Updating sirbrillig/phpcs-variable-analysis (v2.10.0 => v2.10.1): Downloading (100%)        - Updating drupal/coder (8.3.11 => 8.3.12):  Checking out 719ddb16ae
- Updating phpspec/prophecy (1.12.1 => 1.12.2): Downloading (100%)
- Updating symfony/string (v5.2.0 => v5.2.1): Downloading (100%)
- Updating symfony/inflector (v5.2.0 => v5.2.1): Downloading (100%)
- Updating symfony/var-dumper (v4.4.17 => v4.4.18): Downloading (100%)
- Updating drupal/token (1.7.0 => 1.9.0): Downloading (100%)
- Updating league/csv (9.6.1 => 9.6.2): …
```
=> update all dependencies - drupal/token (1.7.0 => 1.9.0)

behat/Features/elasticsearch/search.games.states.facets.feature, web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/GameNodeIndex.php, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/GameNormalizer.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php
Fix the State facets & indexation setup
- #125 
see #125
=> fix release states facets indexation & calculation - #125

composer.lock, config/d8/sync/simple_sitemap.settings.yml, web/modules/custom/gos_site/src/Plugin/simple_sitemap/UrlGenerator/NextJsUrlGenerator.php, web/sites/default/test.settings.php
update all dependencies (including drupal core) & export new config
```
Updating dependencies (including require-dev)
Package operations: 2 installs, 53 updates, 2 removals
- Removing guzzlehttp/streams (3.0.0)
- Removing guzzlehttp/ringphp (1.1.1)
- Updating composer/installers (v1.9.0 => v1.10.0): Downloading (100%)
- Updating symfony/polyfill-php80 (v1.20.0 => v1.22.1): Loading from cache
- Updating symfony/polyfill-intl-normalizer (v1.20.0 => v1.22.1): Loading from cache
- Updating symfony/deprecation-contracts (v2.2.0 => v2.4.0): Loading from cache
- Updating symfony/polyfill-intl-grapheme (v1.20.0 => v1.22.1): Loading from cache
- Updating symfony/string (v5.2.1 => v5.2.6): Loading from …
```
=> update all dependencies (including drupal core) & export new config

CHANGELOG.md, behat/Features/jsonapi/games.feature, behat/Features/jsonapi/page.feature, behat/Features/jsonapi/pages.feature, behat/Features/jsonapi/studios.feature, composer.json, config/d8/sync/gin_login.settings.yml, config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--page.yml, web/modules/custom/gos_default_content/content/node/38e10164-166d-4c76-be68-0a3a48cf2966.json
- add Basic pages to JSON:API 
- add Video Games collection to Gin Login
- close #140
=> add  Basic pages to JSON:API

composer.json, composer.lock, psalm.xml, web/INSTALL.txt, web/README.md, web/example.gitignore, web/modules/README.txt, web/modules/custom/gos_default_content/gos_default_content.info.yml, web/modules/custom/gos_elasticsearch/gos_elasticsearch.info.yml, web/modules/custom/gos_elasticsearch/gos_elasticsearch.services.yml, web/modules/custom/gos_elasticsearch/src/Plugin/rest/ValidatorFactory.php, web/modules/custom/gos_game/gos_game.info.yml, web/modules/custom/gos_migrate/gos_migrate.info.yml, web/modules/custom/gos_rest/gos_rest.info.yml, web/modules/custom/gos_site/gos_site.info.yml, web/modules/custom/gos_test/gos_test.info.yml, web/profiles/README.txt, web/sites/README.txt, web/themes/README.txt
update modules to be compatible with Drupal 9
=> update modules to be compatible with Drupal 9

.github/workflows/ci-cd.yml, Dockerfile
attempts to update to composer v2
=> attempts to update to composer v2

.github/actions/deploy/action.yml, .github/workflows/ci-cd.yml
set job environment during deploy
see https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-environment-name-and-url
=> set job environment during deploy

.github/workflows/ci-cd.yml
remove satackey/action-docker-layer-caching on Github Actions
=> remove satackey/action-docker-layer-caching on Github Actions

README.md, composer.json, composer.lock, config/d8/sync/cdn.settings.yml, config/d8/sync/core.extension.yml, psalm.xml, web/sites/default/development.settings.php
add the CDN module to serve all images via HTTPs
=> add the CDN module to serve all images via HTTPs

.github/workflows/ci-cd.yml, CHANGELOG.md, Dockerfile
use Docker Builtkit on Github Action
=> use Docker Builtkit on Github Action

CHANGELOG.md, config/d8/sync/jsonapi_extras.jsonapi_resource_config.node--game.yml
rename Game Json:api field_cantons to cantons
close Games-of-Switzerland/swissgamesgarden#51
=> rename Game Json:api field_cantons to cantons - Games-of-Switzerland/swissgamesgarden#51

CHANGELOG.md, composer.json, composer.lock
update library marcortola/behat-seo-contexts (3.1.1 => 4.0.0)
=> update library marcortola/behat-seo-contexts (3.1.1 => 4.0.0)

CHANGELOG.md, composer.json, composer.lock
update module drupal/migrate_tools (5.2.0 => 6.0.1)
=> update module drupal/migrate_tools (5.2.0 => 6.0.1)

CHANGELOG.md, composer.lock
update theme drupal/gin (3.0.0-rc1 => 3.0.0-rc2)
=> update theme drupal/gin (3.0.0-rc1 => 3.0.0-rc2)

CHANGELOG.md, config/d8/sync/views.view.content.yml, web/modules/custom/gos_elasticsearch/src/Plugin/rest/ResourceValidator/ElasticGamesResourceValidator.php, web/modules/custom/gos_game/tests/src/Kernel/ReleasesCompilerTest.php, web/modules/custom/gos_site/src/Plugin/Field/FieldWidget/ReleaseDefaultWidget.php, web/sites/default/files/gin-custom.css
add the new Release Type 'Prototype'
- Games-of-Switzerland/swissgamesgarden#132
=> add the new Release Type 'Prototype'

CHANGELOG.md, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/GameNormalizer.php
fix issue when member is deleted leading to un-indexable games
=> fix issue when member is deleted leading to un-indexable games

CHANGELOG.md, composer.json, composer.lock, config/d8/sync/core.extension.yml, config/d8/sync/symfony_mailer.mailer_policy._.yml, config/d8/sync/symfony_mailer.settings.yml, web/modules/custom/gos_site/src/Plugin/simple_sitemap/UrlGenerator/NextJsUrlGenerator.php
Update modules January 2024
- update module drupal/migrate_source_csv (3.5.0 => 3.6.0)
- drupal/migrate_tools (6.0.1 => 6.0.4)
=> Update modules January 2024

CHANGELOG.md, Gemfile, Gemfile.lock, README.md, composer.json, composer.lock, docker/Dockerfile, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticAutocompleteResource.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php
=> update PHP 8.0 -> 8.1

CHANGELOG.md, composer.lock
update phpspec/prophecy-phpunit (v2.0.2 => v2.1.0)
=> update phpspec/prophecy-phpunit (v2.0.2 => v2.1.0)

CHANGELOG.md, composer.json, composer.lock, web/modules/custom/gos_default_content/gos_default_content.info.yml, web/modules/custom/gos_elasticsearch/gos_elasticsearch.info.yml, web/modules/custom/gos_game/gos_game.info.yml, web/modules/custom/gos_migrate/gos_migrate.info.yml, web/modules/custom/gos_rest/gos_rest.info.yml, web/modules/custom/gos_site/gos_site.info.yml, web/modules/custom/gos_test/gos_test.info.yml
Upgrade modules Major version - February 2024
- upgrade module drupal/cdn (3.6.0 => 4.0.2)
=> Upgrade modules Major version - February 2024

docker/Dockerfile
=> fix Docker drush alias

CHANGELOG.md, config/d8/sync/core.extension.yml, config/d8/sync/editor.editor.basic_html.yml, config/d8/sync/editor.editor.full_html.yml, config/d8/sync/filter.format.basic_html.yml, config/d8/sync/filter.format.full_html.yml
enable CKeditor 5 to replace CKeditor 4
=> enable CKeditor 5 to replace CKeditor 4

.github/workflows/ci-cd.yml, CHANGELOG.md, README.md, behat/Features/elasticsearch/search.games.platforms.facets.feature, behat/Features/elasticsearch/search.games.platforms.feature, behat/Features/elasticsearch/search.games.q.feature, behat/Features/elasticsearch/search.games.release_year_range.feature, behat/Features/elasticsearch/search.games.states.feature, scripts/hooks/post-commit
fix obsolete docker-compose command
=> fix obsolete docker-compose command

.github/dependabot.yml
=> Update dependabot.yml to watch tools

.github/workflows/ci-cd.yml, CHANGELOG.md, composer.json, composer.lock, docker/Dockerfile, web/modules/custom/gos_game/tests/src/Kernel/ReleasesCompilerTest.php
=> upgrade from PHP 8.1 -> 8.2

docker-compose.ci.yml, docker-compose.override-example.yml, docker-compose.yml
use arm version of browser selenium container
=> use arm version of browser selenium container

CHANGELOG.md, behat/Features/login/login.feature, composer.json, composer.lock, config/d8/sync/core.extension.yml, config/d8/sync/field.field.block_content.basic.body.yml, config/d8/sync/field.field.node.game.body.yml, config/d8/sync/field.field.node.game.field_credits.yml, config/d8/sync/field.field.node.page.body.yml, config/d8/sync/field.field.node.people.body.yml, config/d8/sync/field.field.node.studio.body.yml, config/d8/sync/hal.settings.yml, config/d8/sync/jsonapi_extras.settings.yml, web/modules/custom/gos_default_content/gos_default_content.info.yml, web/modules/custom/gos_elasticsearch/gos_elasticsearch.info.yml, web/modules/custom/gos_game/gos_game.info.yml, web/modules/custom/gos_game/tests/src/Functional/EntityReleaseNormalizedTest.php, web/modules/custom/gos_game/tests/src/Kernel/ReleasesCompilerTest.php, web/modules/custom/gos_migrate/gos_migrate.info.yml, web/modules/custom/gos_rest/gos_rest.info.yml, web/modules/custom/gos_site/gos_site.info.yml, web/modules/custom/gos_test/gos_test.info.yml
- update static analyzer phpstan dev dependency
=> Update modules for Drupal 10.2

CHANGELOG.md, composer.json, composer.lock
update imbo/behat-api-extension (v2.3.3 => v5.0.0)
=> update imbo/behat-api-extension (v2.3.3 => v5.0.0)

tools/php-deprecation-detector/composer.lock
update dependencies of linter phpdd
=> update dependencies of linter phpdd

CHANGELOG.md, behat/Context/Drupal/XmlContext.php, behat/Features/elasticsearch/search.games.locations.feature, composer.json, composer.lock, web/modules/custom/gos_elasticsearch/src/Plugin/rest/ResourceValidator/ElasticGamesResourceValidator.php, web/modules/custom/gos_site/src/Plugin/simple_sitemap/UrlGenerator/NextJsUrlGenerator.php, web/sites/default/default.settings.php
=> Update to Drupal 10.4.1

CHANGELOG.md, web/modules/custom/gos_elasticsearch/src/Plugin/Normalizer/GameNormalizer.php
improve Games Normalization for Elasticsearch by supporting nullable entities
=> improve Games Normalization for Elasticsearch by supporting nullable entities

.github/workflows/ci-cd.yml, CHANGELOG.md, composer.json, config/d8/sync/core.extension.yml, docker/Dockerfile, tools/php-cs-fixer/composer.lock, web/modules/custom/gos_elasticsearch/src/Plugin/ElasticsearchIndex/NodeIndexBase.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/ResourceValidator/ElasticGamesResourceValidator.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticAutocompleteResource.php, web/modules/custom/gos_elasticsearch/src/Plugin/rest/resource/ElasticGamesResource.php, web/modules/custom/gos_game/src/CompletenessCalculator.php, web/modules/custom/gos_migrate/src/Plugin/migrate/process/StoresMapper.php, web/modules/custom/gos_migrate/src/Plugin/migrate/source/BaseRowExploded.php, web/modules/custom/gos_migrate/src/Plugin/migrate/source/Cantons.php, web/modules/custom/gos_migrate/src/Plugin/migrate/source/Genres.php, web/modules/custom/gos_migrate/src/Plugin/migrate/source/Languages.php, web/modules/custom/gos_migrate/src/Plugin/migrate/source/Locations.php, web/modules/custom/gos_migrate/src/Plugin/migrate/source/People.php, web/modules/custom/gos_migrate/src/Plugin/migrate/source/Platforms.php, web/modules/custom/gos_migrate/src/Plugin/migrate/source/Publishers.php, web/modules/custom/gos_migrate/src/Plugin/migrate/source/Sponsors.php, web/modules/custom/gos_migrate/src/Plugin/migrate/source/Studios.php, web/modules/custom/gos_migrate/src/Plugin/migrate/source/Videos.php, web/modules/custom/gos_site/src/UrlBuilderNextJs.php
upgrade from PHP 8.2 -> 8.3 -
- Games-of-Switzerland/swissgamesgarden#164
=> upgrade from PHP 8.2 -> 8.3 - Games-of-Switzerland/swissgamesgarden#164
